# Generated by Django 2.2 on 2022-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_product',
            field=models.CharField(default='', max_length=200),
        ),
    ]
