# Generated by Django 4.0.3 on 2022-04-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Subtotal',
            field=models.FloatField(default=0),
        ),
    ]
