# Generated by Django 4.0.3 on 2022-04-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Subtotal',
            new_name='subtotal',
        ),
    ]
