# Generated by Django 4.0.3 on 2022-04-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_subtotal_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
