# Generated by Django 4.0.3 on 2022-04-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
